### ISSUE TITLE
safari-pinned-tab.svg not created from png source

### ISSUE THREAD

**Issue by robnagler** [afaundez/jekyll-favicon#16]
**Describe the bug**
When providing a png source (assuming), the header generated includes:

```html
<link rel="mask-icon" color="#ffffff" href="/assets/i/safari-pinned-tab.svg">
```

However, there's no such file so an error appears in the logs.

**To Reproduce**

Use any PNG as the source and run.

**Expected behavior**

I don't expect and SVG to be created. I just think the head line should not be added.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 Fedora

**Smartphone (please complete the following information):**
 Safari

**Additional context**
n/a

**Comment by afaundez** [comment]
@robnagler the version 0.2.5 has fixed this issue. Let me know if works!

**Comment by robnagler** [comment]
Thanks @afaundez. Works great!
