### ISSUE TITLE
Transparent background in SVG becomes black

### ISSUE THREAD

**Issue by Steven-Roberts** [afaundez/jekyll-favicon#19]
I have been using version 0.2.4 to generate the favicon for my site from an SVG with a transparent background with no problems.  After upgrading to 0.2.5, however, the generated favicon.ico now has a black background.  I've tried a couple different SVGs with transparent backgrounds and the generated icon always has a black background.

**Comment by afaundez** [comment]
Hi @Steven-Roberts, thanks for reporting this. I'm glad this gem has been useful. Currently, I'm refactoring all in order to have a clear code and more tests.

I successfully reproduced the problem. I'll look for a workaround now.

**Comment by PanderMusubi** [comment]
Here same problem, looking forward to the workaround.

**Comment by afaundez** [comment]
@Steven-Roberts, @PanderMusubi 

I've just publish a new version, 0.2.6, which fixes the issue.

I'm working on version 1.0.0 that I hope will make easier to debug and test features.

Thanks again for reporting and using the gem!
