### ISSUE TITLE
Transparent background in SVG becomes white

### ISSUE THREAD

**Issue by Steven-Roberts** [afaundez/jekyll-favicon#22]
This is basically identical to #19 but now the background is white.  I don't remember if 0.2.6 has always been like this or not.  Version 0.2.4 still seems to work fine in the meantime.

**Comment by alexpls** [comment]
Seeing the same issue with version `0.2.6` and transparent backgrounds in PNG images.

**Comment by afaundez** [comment]
Hey guys, thanks for reporting this. I’ll be working on it today.

**Comment by afaundez** [comment]
Hi guys, sorry for the late response. [0.2.7](https://github.com/afaundez/jekyll-favicon/tree/0.2.7) fixes the issue.

The [example site](https://afaundez.gitlab.io/jekyll-favicon-example/) is running the fix while using an SVG source. As you can see on it, now the generator does not add a default background color to the PNG files.

Thanks for using the gem and reporting issues.

**Comment by alexpls** [comment]
Thanks so much @afaundez! I'll upgrade to `0.2.7` later this week.

Really appreciate your work on this plugin, it's saved me heaps of time ❤️
