### ISSUE TITLE
Incompatible with `jekyll-minifier`?

### ISSUE THREAD

**Issue by rohandebsarkar** [afaundez/jekyll-favicon#37]
**Describe the bug**
I was trying to use this plugin, but encountered with a bug. After trying to read the log, I found something with `jekyll-minifier`. I tried removing the `jekyll-mifier` plugin. This plugin works smoothly. But it gives an error with `jrkyll minifier`

**To Reproduce**
Use this plugin with [`jekyll-minifier`](https://github.com/digitalsparky/jekyll-minifier)

**Environment:**
 - OS: Archlinux
 - Ruby version: 3.0.4p208
 - Bundler version: 2.3.10
 - Jekyll version: 4.2.1
 - Jekyll Favicon version: 1.0.0

**Log**
```
/usr/lib/ruby/gems/3.0.0/gems/jekyll-favicon-1.0.0/lib/jekyll/favicon/static_file/convertible.rb:68:in `copy_file': wrong number of arguments (given 2, expected 1) (ArgumentError)
        from /usr/lib/ruby/gems/3.0.0/gems/jekyll-minifier-0.1.10/lib/jekyll-minifier.rb:223:in `write'
        from /usr/lib/ruby/gems/3.0.0/gems/jekyll-favicon-1.0.0/lib/jekyll/favicon/static_file/convertible.rb:61:in `write'
        from /usr/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:231:in `block in write'
        from /usr/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:358:in `block (2 levels) in each_site_file'
        from /usr/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:357:in `each'
        from /usr/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:357:in `block in each_site_file'
        from /usr/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:356:in `each'
        from /usr/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:356:in `each_site_file'
        from /usr/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:230:in `write'
        from /usr/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:82:in `process'
        from /usr/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:28:in `process_site'
        from /usr/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:65:in `build'
        from /usr/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:36:in `process'
        from /usr/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /usr/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
        from /usr/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /usr/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /usr/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /usr/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /usr/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /usr/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /usr/lib/ruby/gems/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /usr/lib/ruby/gems/3.0.0/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
        from /usr/bin/jekyll:25:in `load'
        from /usr/bin/jekyll:25:in `<top (required)>'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.10/lib/bundler/cli.rb:483:in `exec'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.10/lib/bundler/cli.rb:31:in `dispatch'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.10/lib/bundler/cli.rb:25:in `start'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.10/exe/bundle:48:in `block in <top (required)>'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.10/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.3.10/exe/bundle:36:in `<top (required)>'
        from /usr/bin/bundle:25:in `load'
        from /usr/bin/bundle:25:in `<main>'
```

**Comment by rohandebsarkar** [comment]
This issue is maybe created since both the classes have same name in the following file:

https://github.com/afaundez/jekyll-favicon/blob/8ac2ca55ea94817153a1733d4d660f67d01b79cb/lib/jekyll/favicon/static_file/convertible.rb#L8

**Comment by afaundez** [comment]
@rohandebsarkar, thanks for the feedback.

I was checking, and apparently, the issue comes from both gems modifying the `Jekyll::StaticFile` class. I create a subclass and then overwrite its methods, but it seems I get the [superclass modified by minifier](https://github.com/digitalsparky/jekyll-minifier/blob/be6d0d56b1fc9eade93b4d5a4933d0340aee1d71/lib/jekyll-minifier.rb#L188).

I'll try to find a workaround, maybe excluding favicon assets when minifying like [this](https://github.com/digitalsparky/jekyll-minifier/issues/42#issuecomment-414954845)

**Comment by rohandebsarkar** [comment]
> @rohandebsarkar, thanks for the feedback.
> 
> I was checking, and apparently, the issue comes from both gems modifying the `Jekyll::StaticFile` class. I create a subclass and then overwrite its methods, but it seems I get the [superclass modified by minifier](https://github.com/digitalsparky/jekyll-minifier/blob/be6d0d56b1fc9eade93b4d5a4933d0340aee1d71/lib/jekyll-minifier.rb#L188).
> 
> I'll try to find a workaround, maybe excluding favicon assets when minifying like [this](https://github.com/digitalsparky/jekyll-minifier/issues/42#issuecomment-414954845)

Hi @afaundez!, thank you for replying.

I tried excluding the favicon assets from minifying, but still the error persists.

**Comment by motdotla** [comment]
+1 I also just ran into this issue.

Great Jekyll Plugin!

**Comment by afaundez** [comment]
Thank @motdotla!

I have to admit that I've tried to solve this unsuccessfully. I haven't found a way to load de original Jekyll::StaticFile without the Minifier modifications.
I'll continue trying. Any idea is more than welcome!

**Comment by afaundez** [comment]
I'll close this issue and label it won't fix, considering I couldn't find a way to bypass the way jekyll-minifier modifies the original Static File class even if the file it's excluded (it adds an [extra parameter](https://github.com/digitalsparky/jekyll-minifier/blob/master/lib/jekyll-minifier.rb#L191) to the [jekyll class](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/static_file.rb#L191))

I'll welcome any idea to reopen the issue!
