### ISSUE TITLE
Infinite loop of favicon generation

### ISSUE THREAD

**Issue by hacketiwack** [afaundez/jekyll-favicon#39]
**Describe the bug**
On macOS, when ImageMagick is installed along with Inkscape through brew.sh, the generation of a favicon from a SVG image never ends: infinite processes of Inkscape are spawn one after another.

**To Reproduce**
1. Install ImageMagick and Inkscape through brew.
```
brew install imagemagick inkscape
```
3. Install jekyll-favicon as mentioned in the documentation.
4. Proceed with the build
```
bundle exec jekyll build
```
5. The build never stops

**Expected behavior**
Once the build is launched, it should stop after a few seconds.

**Screenshots**
Not applicable.

**Environment:**
 - macOS 13.2.1 (22D68)
 - ruby 3.2.1 (2023-02-08 revision 31819e82c8) [arm64-darwin22]
 - Bundler version 2.4.7
 - jekyll 4.3.2
 - jekyll-favicon 1.1.0

**Comment by afaundez** [comment]
Hi @hacketiwack, thank you for reporting this.

I tried reproducing the error in the same environment. I followed the Jekyll instructions to create a new project and then added the Jekyll Favicon as instructed in this repo, and it worked fine. I noticed, though, that when building, the Inkscape icon appears and disappears in the dock repeatedly, but, in my case, it stopped eventually.

Please upload a repo with a minimal example so I can run the same on my laptop.

**Comment by hacketiwack** [comment]
OK, I tried again and this time let it finish. After around 250 seconds, the build stops.
So this is not per se an infinite loop.
I need to check if there is a post or some plugin that is causing this.
I'll keep you posted.

**Comment by hacketiwack** [comment]
I have more information to share. It seems that whenever I add the tag `{% favicon %}` in my header, each and every page that ends up being generated into an index.html provokes the generation of the favicons.
Is it really so that this plugin generates the favicon for each index.html?

**Important note:** If the source file for the favicon is a `PNG`instead of an `SVG`, the issue doesn't happen.

**Comment by hacketiwack** [comment]
@afaundez, please find [here](https://github.com/hacketiwack/minima) is a version of the minima theme with the inclusion of jekyll-favicon that provokes the behaviour mentioned in this issue.

**Comment by afaundez** [comment]
That's a bug. I open another issue with your info. Thanks!
