### ISSUE TITLE
Extend documentation

### ISSUE THREAD

**Issue by PanderMusubi** [afaundez/jekyll-favicon#9]
Please extent the documentation that also the package `librsvg2-bin` is installed as prerequisite for Ubuntu/Debian.

**Comment by afaundez** [comment]
Thanks, @PanderMusubi.
What Ubuntu/Debian version are you using? I would like to reproduce it and add it to Travis.

**Comment by PanderMusubi** [comment]
18.04

**Comment by afaundez** [comment]
@PanderMusubi I run Lubuntu 18.04 on Virtualbox (try without install mode) and I didn't have problems with the package you mentioned.

I installed,

```sh
sudo apt install git ruby-bundler ruby-dev build-essential imagemagick
```

and I was able to run this [minimal example](https://gitlab.com/afaundez/jekyll-favicon-example.git) without a problem.

To be sure, I run `dpkg -l | grep librsvg2-bin` and the result was empty.

Can you tell me more about your setup in order to reproduce the issue?

**Comment by PanderMusubi** [comment]
Ran into it again:

    jekyll s
    ...
          Generating... 
    jekyll 3.8.5 | Error:  `convert -flatten -background none -density 2000 -resize 1024x1024 /xxx/yyy/favicon.svg /tmp/favicon-template20190318-23721-1m2fc48.png` failed with error:
    convert-im6.q16: delegate failed `'rsvg-convert' -o '%o' '%i'' @ error/delegate.c/InvokeDelegate/1919.
    convert-im6.q16: unable to open file `/tmp/magick-23723CQpRLVRpIjZz': No such file or directory @ error/constitute.c/ReadImage/544.
    convert-im6.q16: no images defined `/tmp/favicon-template20190318-23721-1m2fc48.png' @ error/convert.c/ConvertImageCommand/3258.

No result for

    which rsvg-convert

When typing

    rsvg-convert

I get

    Command 'rsvg-convert' not found, but can be installed with:
    
    sudo apt install librsvg2-bin

Reason might be that I do not install suggested or recommended packages, see

    more /etc/apt/apt.conf
    APT::Install-Recommends "false";
    APT::Install-Suggests "false";

**Comment by afaundez** [comment]
@PanderMusubi I added the comment on the Readme. Thanks again for the details!
